---
- hosts: all
  roles:
    - generic_acme_role
  vars:
    generic_acme_issue_domain:
      - example.com
      - example.org
    generic_acme_priv_key_path: /home/user/
    generic_acme_container_additional_env:
      DEPLOY_DOCKER_CONTAINER_LABEL: "sh.acme.autoload.domain=example.com"
      DEPLOY_DOCKER_CONTAINER_KEY_FILE: "/etc/ssl/certsexample.org/key.pem"
      DEPLOY_DOCKER_CONTAINER_CERT_FILE: "/etc/ssl/certs/example.org/cert.pem"
      DEPLOY_DOCKER_CONTAINER_CA_FILE: "/etc/ssl/certs/example.org/ca.pem"
      DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE: "/etc/ssl/certs/example.org/full.pem"
      DEPLOY_DOCKER_CONTAINER_RELOAD_CMD: "systemctl restart apache2"
      DEPLOY_DOCKER_CONTAINER_FQDN: "example.com"